# Generated by Django 4.2.1 on 2023-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocare_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pt1_head',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
