# Generated by Django 4.2.1 on 2023-07-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocare_data', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
