# Generated by Django 4.2.1 on 2023-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocare_data', '0006_alter_blog_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_mail', models.CharField(max_length=255)),
                ('user_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('user_address', models.TextField()),
                ('user_state', models.CharField(max_length=255)),
                ('user_country', models.CharField(max_length=255)),
                ('delivery_mail', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('delivery_address', models.TextField()),
                ('delivery_state', models.CharField(max_length=255)),
                ('delivery_country', models.CharField(max_length=255)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
