# Generated by Django 4.2.1 on 2023-07-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocare_data', '0007_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='user_id',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
