# Generated by Django 4.2.1 on 2023-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocare_data', '0008_distributor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='delivery_city',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributor',
            name='delivery_pin_code',
            field=models.CharField(default='0', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_city',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_pin_code',
            field=models.CharField(default='0', max_length=8),
            preserve_default=False,
        ),
    ]
