# Generated by Django 4.2.1 on 2023-07-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biocare_data', '0009_distributor_delivery_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='password',
        ),
    ]
