# Generated by Django 4.2.1 on 2023-07-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocare_data', '0011_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_1',
        ),
        migrations.AddField(
            model_name='product',
            name='price_qty_1',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
