# Generated by Django 4.2.1 on 2023-07-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocare_data', '0012_rename_price_product_price_1_product_price_qty_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_2',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_3',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_qty_2',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_qty_3',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
